# Generated by Django 5.1.1 on 2024-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_shop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=3, verbose_name='статус получения заказов'),
        ),
    ]
